package com.betadb.gui.sql.filter;

import javax.swing.JTable;
import javax.swing.RowFilter;

/**
 *
 * @author parmstrong
 */
public class ColumnFilterPanel extends javax.swing.JPanel
{
	/**
	 * Creates new form ColumnFilterDialog
	 */
	public ColumnFilterPanel(JTable jTable)
	{
		initComponents();

		cbColumn.addItem("--Select--");
		for (int i = 0; i < jTable.getColumnCount(); i++)
			cbColumn.addItem(new DataColumn(i, jTable.getColumnName(i)));

		cbOperation.addItem(RowFilter.ComparisonType.EQUAL);
	}

	public ColumnFilterPanel(JTable jTable, RowFilterData rowFilter)
	{
		this(jTable);

		txtValue.setText(rowFilter.getValue().toString());
		cbColumn.setSelectedIndex(rowFilter.getColumn()+1);//adding 1 because we stuffed a dummy entry for the first slot
		cbOperation.setSelectedItem(rowFilter.getComparisonType());

	}

	public RowFilterData getRowFilter()
	{
		Object selectedItem = cbColumn.getSelectedItem();
		if(selectedItem instanceof DataColumn)
		{	
			DataColumn column = (DataColumn) cbColumn.getSelectedItem();			
			return new RowFilterData(column.getIndex(), RowFilter.ComparisonType.EQUAL, txtValue.getText());
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbOperation = new javax.swing.JComboBox();
        txtValue = new javax.swing.JTextField();
        cbColumn = new javax.swing.JComboBox();
        lnkDelete = new org.jdesktop.swingx.JXHyperlink();

        cbOperation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">", "<>" }));

        lnkDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/betadb/gui/icons/delete.png"))); // NOI18N
        lnkDelete.setText("");
        lnkDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lnkDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOperation, 0, 93, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnkDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lnkDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lnkDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lnkDeleteActionPerformed
    {//GEN-HEADEREND:event_lnkDeleteActionPerformed
		this.getParent().remove(this);
    }//GEN-LAST:event_lnkDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbColumn;
    private javax.swing.JComboBox cbOperation;
    private org.jdesktop.swingx.JXHyperlink lnkDelete;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
