/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betadb.gui.sql.filter;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.Lists;
import com.google.common.collect.Multimap;
import com.google.inject.Singleton;
import java.awt.Component;
import java.util.Collection;
import java.util.List;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author parmstrong
 */
@Singleton
public class ColumnFilterDialog extends javax.swing.JDialog
{
	Multimap<JTable, RowFilterData> filters = HashMultimap.create();
	JTable jTable;

	public ColumnFilterDialog(JTable jTable)
	{
		initComponents();
		this.jTable = jTable;
	}

	public void initiate()
	{		
		pnlFilters.removeAll();

		Collection<RowFilterData> tableFilters = filters.get(jTable);
		for (RowFilterData tableFilter : tableFilters)
			pnlFilters.add(new ColumnFilterPanel(jTable, tableFilter));
		pnlFilters.add(new ColumnFilterPanel(jTable));

		this.pack();
		this.setVisible(true);
	}

	public void clearFilters()
	{
		filters.removeAll(jTable);
		applyFilters();		
	}	
		
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */

	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnApply = new javax.swing.JButton();
        pnlFilters = new javax.swing.JPanel();
        btnAddFilterCriteria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter");

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnApplyActionPerformed(evt);
            }
        });

        pnlFilters.addContainerListener(new java.awt.event.ContainerAdapter()
        {
            public void componentRemoved(java.awt.event.ContainerEvent evt)
            {
                pnlFiltersComponentRemoved(evt);
            }
        });
        pnlFilters.setLayout(new javax.swing.BoxLayout(pnlFilters, javax.swing.BoxLayout.PAGE_AXIS));

        btnAddFilterCriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/betadb/gui/icons/add.png"))); // NOI18N
        btnAddFilterCriteria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddFilterCriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAddFilterCriteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply)
                    .addComponent(btnAddFilterCriteria)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnApplyActionPerformed
    {//GEN-HEADEREND:event_btnApplyActionPerformed
		
		filters.removeAll(jTable);

		for (Component component : pnlFilters.getComponents())
		{
			if (component instanceof ColumnFilterPanel)
			{
				RowFilterData rowFilter = ((ColumnFilterPanel) component).getRowFilter();
				if(rowFilter != null)
					filters.put(jTable, rowFilter);
			}
		}
		
		applyFilters();
    }//GEN-LAST:event_btnApplyActionPerformed

	private void applyFilters()
	{
		List<RowFilter<Object, Object>> columnFilters = Lists.newArrayList();
		filters.get(jTable);
		for (RowFilterData rowFilterData : filters.get(jTable))
			columnFilters.add(RowFilter.regexFilter(rowFilterData.getValue().toString(), rowFilterData.getColumn()));
		
		
		TableRowSorter sorter = (TableRowSorter) jTable.getRowSorter();
		if (columnFilters.isEmpty())
			sorter.setRowFilter(null);
		else if (columnFilters.size() == 1)
			sorter.setRowFilter(columnFilters.get(0));
		else
			sorter.setRowFilter(RowFilter.andFilter(columnFilters));

		this.setVisible(false);

	}


    private void btnAddFilterCriteriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddFilterCriteriaActionPerformed
    {//GEN-HEADEREND:event_btnAddFilterCriteriaActionPerformed
		pnlFilters.add(new ColumnFilterPanel(jTable));
		pack();
		revalidate();


    }//GEN-LAST:event_btnAddFilterCriteriaActionPerformed

    private void pnlFiltersComponentRemoved(java.awt.event.ContainerEvent evt)//GEN-FIRST:event_pnlFiltersComponentRemoved
    {//GEN-HEADEREND:event_pnlFiltersComponentRemoved
		pack();
		revalidate();
    }//GEN-LAST:event_pnlFiltersComponentRemoved

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFilterCriteria;
    private javax.swing.JButton btnApply;
    private javax.swing.JPanel pnlFilters;
    // End of variables declaration//GEN-END:variables
}
