/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Jun 14, 2011, 3:22:35 PM
 */
package com.betadb.gui;

import com.betadb.gui.connection.DbConnection;
import com.betadb.gui.connection.ConnectionsPanel;
import com.betadb.gui.events.Event;
import com.betadb.gui.events.EventListener;
import com.betadb.gui.events.EventManager;
import com.betadb.gui.objectdetail.ObjectDetailsPanel;
import com.betadb.gui.sql.SqlPanel;
import java.awt.BorderLayout;
import net.infonode.docking.RootWindow;
import net.infonode.docking.SplitWindow;
import net.infonode.docking.TabWindow;
import net.infonode.docking.View;
import net.infonode.docking.util.DockingUtil;
import net.infonode.docking.util.ViewMap;
import static com.betadb.gui.events.Event.*;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author parmstrong
 */
public class MainWindow extends javax.swing.JFrame implements EventListener {

    private RootWindow rootWindow;
    private TabWindow tabWindow;
    private static MainWindow mainwindow;

    public static MainWindow getInstance() {
        if (mainwindow == null) {
            mainwindow = new MainWindow();
        }
        return mainwindow;
    }

    /**
     * Creates new form Main
     */
    public MainWindow() {
        this.setTitle("Beta-DB SQL Editor");
        initComponents();
//        GraphicsEnvironment localEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
//        GraphicsDevice defaultDevice = localEnvironment.getDefaultScreenDevice();
//        defaultDevice.setFullScreenWindow(this);
		this.setSize(new Dimension(1900,1000));
        EventManager.getInstance().addEventListener(this);
        tabWindow = new TabWindow();
        ViewMap viewMap = new ViewMap();
        viewMap.addView(0, new View("Connections", null, ConnectionsPanel.getInstance()));
        viewMap.addView(1, new View("ObjectDetails", null, ObjectDetailsPanel.getInstance()));		

        rootWindow = DockingUtil.createRootWindow(viewMap, true);
        rootWindow.setWindow(new SplitWindow(true, 0.15f, new SplitWindow(false, .80f, viewMap.getView(0), viewMap.getView(1)), tabWindow));

        rootWindow.setVisible(true);
        this.setLayout(new BorderLayout());
        this.add(rootWindow, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainWindow.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void EventOccurred(Event event, Object value) {
        if (event == SQL_CONNECTION_REQUESTED) {
            DbConnection connectionInfo = (DbConnection) value;
            View view = new View(connectionInfo.getDataSourceKey() + " (" + connectionInfo.getDbInfo().getDbName() + ")", null, new SqlPanel(connectionInfo));
            tabWindow.addTab(view);
        }
    }
}
