/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessagePanel.java
 *
 * Created on Jun 23, 2011, 4:44:57 PM
 */

package com.betadb.gui.sql;

import java.awt.Dimension;
import java.awt.Rectangle;

/**
 *
 * @author parmstrong
 */
public class MessagePanel extends javax.swing.JPanel {

    /** Creates new form MessagePanel */
    public MessagePanel() 
	{		
        initComponents();		
		setMinimumSize(new Dimension(70, 70));		
    }
	
	public void setMessage(String message)
	{
		pnlText.setText(message);
	}
	
	public void addMessage(String message)
	{
		pnlText.setText(message+"\n"+pnlText.getText());
		pnlText.scrollRectToVisible(new Rectangle(0, 0, 1, 1));
	}
			

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlText = new javax.swing.JEditorPane();

        pnlText.setPreferredSize(new java.awt.Dimension(20, 24));
        jScrollPane1.setViewportView(pnlText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane pnlText;
    // End of variables declaration//GEN-END:variables
}
