/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betadb.gui.connection;

import com.betadb.gui.MainWindow;
import com.betadb.gui.table.util.renderer.ColumnClassTableCellRenderer;
import com.betadb.gui.table.util.renderer.RendererUtils;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parmstrong
 */
public class TablePrivileges extends javax.swing.JDialog
{
	private DefaultTableModel model;
	private static TablePrivileges instance;

	public static TablePrivileges getInstance()
	{
		if (instance == null)
			instance = new TablePrivileges();
		return instance;
	}

	/**
	 * Creates new form TablePrivileges
	 */
	private TablePrivileges()
	{
		super(MainWindow.getInstance());

		initComponents();

		model = (DefaultTableModel)jTable1.getModel();
		this.setTitle("Table Privileges");
		jTable1.setAutoCreateRowSorter(true);
		

	}

	public void show(List<Map<String,String>> data)
	{	
		String[] columnNames = data.get(0).keySet().toArray(new String[0]);
		String[][] convertedData = new String[data.size()][columnNames.length];

		for (int i = 0; i < data.size(); i++)
		{
			Map<String, String> row = data.get(i);
			for (int j = 0; j < columnNames.length; j++)
				convertedData[i][j] = row.get(columnNames[j]);
		}
		
		model.setDataVector(convertedData, columnNames);
		RendererUtils.formatColumns(jTable1, new ColumnClassTableCellRenderer());
		this.setVisible(true);
	}



	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
