/*
 * SqlPanel.java
 *
 * Created on Jun 21, 2011, 3:04:57 PM
 */

package com.clearwateranalytics.betadb.gui.sql;

import com.clearwateranalytics.betadb.gui.connection.ConnectionInfo;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JSplitPane;
import javax.swing.KeyStroke;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author parmstrong
 */
public class SqlPanel extends javax.swing.JPanel 
{
	private final EditorPanel editorPanel;
	private final ResultsPanel resultsPanel;
	private final JFileChooser fileChooser;
	private String filePath;
	
	
	
    /** Creates new form SqlPanel */
    public SqlPanel(ConnectionInfo connectionInfo) 
	{			
        initComponents();
		
		
       
		
		
		fileChooser = new JFileChooser();
		resultsPanel = new ResultsPanel(connectionInfo);
		editorPanel = new EditorPanel(connectionInfo);
		JSplitPane split = new JSplitPane(JSplitPane.VERTICAL_SPLIT, editorPanel, resultsPanel);
		split.setAlignmentX(Component.LEFT_ALIGNMENT);
		pnlMain.add(split);	
		this.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("F5"),"execute");
		this.getActionMap().put("execute", new AbstractAction() 
		{
			@Override
			public void actionPerformed(ActionEvent ae)
			{
				executeSql(false);
			}
		});
		
		this.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("control S"), "PRESS");
        this.getActionMap().put("PRESS", new AbstractAction() 
		{
			@Override
			public void actionPerformed(ActionEvent ae)
			{
				save(false);
			}
		});
    }

	
	private void executeSql(boolean executeAll)
	{		
		String sql = editorPanel.getSql(executeAll);
		resultsPanel.getResults(sql);
	}
	
	private void save(boolean saveAs)
	{
		String sql = editorPanel.getSql(true);
		File file = null;
		if (filePath == null || saveAs)
		{
			int response = fileChooser.showSaveDialog(this);
			if (response == JFileChooser.APPROVE_OPTION)
			{
				file = fileChooser.getSelectedFile();
				filePath = file.getPath();
			}
			else if(response == JFileChooser.CANCEL_OPTION)
				return;
		}
		else
			file = new File(filePath);
		
		
		FileWriter fw = null;
		try
		{
			
			fw = new FileWriter(file);
			fw.write(sql);
		}
		catch (IOException ex)
		{
			Logger.getLogger(SqlPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
		finally
		{
			try
			{
				fw.close();
			}
			catch (IOException ex)
			{
				Logger.getLogger(SqlPanel.class.getName()).log(Level.SEVERE, null, ex);
			}
		}	
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnExecute = new javax.swing.JButton();
        btnExecuteAll = new javax.swing.JButton();
        btnCancelQuery = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setAlignmentX(0.0F);

        btnExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/execute.png"))); // NOI18N
        btnExecute.setToolTipText("Run");
        btnExecute.setFocusable(false);
        btnExecute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExecute);

        btnExecuteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/executeAll.png"))); // NOI18N
        btnExecuteAll.setToolTipText("Run All");
        btnExecuteAll.setFocusable(false);
        btnExecuteAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecuteAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExecuteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteAllActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExecuteAll);

        btnCancelQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/cancel.png"))); // NOI18N
        btnCancelQuery.setToolTipText("Cancel");
        btnCancelQuery.setFocusable(false);
        btnCancelQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelQueryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelQuery);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/disksave.png"))); // NOI18N
        btnSave.setToolTipText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/disksaveadvanced.png"))); // NOI18N
        btnSaveAs.setToolTipText("Save As");
        btnSaveAs.setFocusable(false);
        btnSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveAs);

        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clearwateranalytics/betadb/gui/icons/folder_page.png"))); // NOI18N
        btnOpenFile.setToolTipText("Open");
        btnOpenFile.setFocusable(false);
        btnOpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpenFile);

        add(jToolBar1);

        pnlMain.setLayout(new javax.swing.BoxLayout(pnlMain, javax.swing.BoxLayout.PAGE_AXIS));
        add(pnlMain);
    }// </editor-fold>//GEN-END:initComponents

	private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExecuteActionPerformed
	{//GEN-HEADEREND:event_btnExecuteActionPerformed
		executeSql(false);
	}//GEN-LAST:event_btnExecuteActionPerformed

	private void btnCancelQueryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelQueryActionPerformed
	{//GEN-HEADEREND:event_btnCancelQueryActionPerformed
		resultsPanel.cancelQuery();
	}//GEN-LAST:event_btnCancelQueryActionPerformed

	private void btnExecuteAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExecuteAllActionPerformed
	{//GEN-HEADEREND:event_btnExecuteAllActionPerformed
		executeSql(true);
	}//GEN-LAST:event_btnExecuteAllActionPerformed

	private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenFileActionPerformed
	{//GEN-HEADEREND:event_btnOpenFileActionPerformed
		int returnVal = fileChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			FileReader reader = null;
			try
			{
				File file = fileChooser.getSelectedFile();
				filePath = file.getPath();				
				BufferedReader buf = new BufferedReader(new FileReader(file));
				StringBuilder builder = new StringBuilder();
				String curLine = buf.readLine();
				while(curLine != null)
				{
					builder.append(curLine);
					builder.append("\n");
					curLine = buf.readLine();
				}
				editorPanel.appendSql(builder.toString());
			}
			catch (Exception ex)
			{
				Logger.getLogger(SqlPanel.class.getName()).log(Level.SEVERE, null, ex);
			}
			finally
			{
				try
				{
					reader.close();
				}
				catch (IOException ex)
				{
					Logger.getLogger(SqlPanel.class.getName()).log(Level.SEVERE, null, ex);
				}
			}			
		}
	}//GEN-LAST:event_btnOpenFileActionPerformed

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
	{//GEN-HEADEREND:event_btnSaveActionPerformed
		save(false);
		
	}//GEN-LAST:event_btnSaveActionPerformed

	private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveAsActionPerformed
	{//GEN-HEADEREND:event_btnSaveAsActionPerformed
		save(true);
	}//GEN-LAST:event_btnSaveAsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelQuery;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnExecuteAll;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
